/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TalentsRouteImport } from './routes/talents'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVotesRouteImport } from './routes/dashboard.votes'
import { Route as DashboardTalentsRouteImport } from './routes/dashboard.talents'
import { Route as DashboardSuggestionsRouteImport } from './routes/dashboard.suggestions'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardAdminVerifyRouteImport } from './routes/dashboard.admin.verify'
import { Route as DashboardAdminReportsRouteImport } from './routes/dashboard.admin.reports'
import { Route as DashboardAdminFundingRouteImport } from './routes/dashboard.admin.funding'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsRoute = TalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVotesRoute = DashboardVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTalentsRoute = DashboardTalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuggestionsRoute = DashboardSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminVerifyRoute = DashboardAdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminReportsRoute = DashboardAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminFundingRoute = DashboardAdminFundingRouteImport.update({
  id: '/admin/funding',
  path: '/admin/funding',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/reports': typeof ReportsRoute
  '/talents': typeof TalentsRoute
  '/transparency': typeof TransparencyRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/talents': typeof DashboardTalentsRoute
  '/dashboard/votes': typeof DashboardVotesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/funding': typeof DashboardAdminFundingRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/verify': typeof DashboardAdminVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/reports': typeof ReportsRoute
  '/talents': typeof TalentsRoute
  '/transparency': typeof TransparencyRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/talents': typeof DashboardTalentsRoute
  '/dashboard/votes': typeof DashboardVotesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/funding': typeof DashboardAdminFundingRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/verify': typeof DashboardAdminVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/reports': typeof ReportsRoute
  '/talents': typeof TalentsRoute
  '/transparency': typeof TransparencyRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/talents': typeof DashboardTalentsRoute
  '/dashboard/votes': typeof DashboardVotesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/funding': typeof DashboardAdminFundingRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/verify': typeof DashboardAdminVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/events'
    | '/reports'
    | '/talents'
    | '/transparency'
    | '/dashboard/events'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/dashboard/suggestions'
    | '/dashboard/talents'
    | '/dashboard/votes'
    | '/dashboard/'
    | '/dashboard/admin/funding'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/reports'
    | '/talents'
    | '/transparency'
    | '/dashboard/events'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/dashboard/suggestions'
    | '/dashboard/talents'
    | '/dashboard/votes'
    | '/dashboard'
    | '/dashboard/admin/funding'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/verify'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/events'
    | '/reports'
    | '/talents'
    | '/transparency'
    | '/dashboard/events'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/dashboard/suggestions'
    | '/dashboard/talents'
    | '/dashboard/votes'
    | '/dashboard/'
    | '/dashboard/admin/funding'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  ReportsRoute: typeof ReportsRoute
  TalentsRoute: typeof TalentsRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents': {
      id: '/talents'
      path: '/talents'
      fullPath: '/talents'
      preLoaderRoute: typeof TalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/votes': {
      id: '/dashboard/votes'
      path: '/votes'
      fullPath: '/dashboard/votes'
      preLoaderRoute: typeof DashboardVotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/talents': {
      id: '/dashboard/talents'
      path: '/talents'
      fullPath: '/dashboard/talents'
      preLoaderRoute: typeof DashboardTalentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suggestions': {
      id: '/dashboard/suggestions'
      path: '/suggestions'
      fullPath: '/dashboard/suggestions'
      preLoaderRoute: typeof DashboardSuggestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/verify': {
      id: '/dashboard/admin/verify'
      path: '/admin/verify'
      fullPath: '/dashboard/admin/verify'
      preLoaderRoute: typeof DashboardAdminVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/reports': {
      id: '/dashboard/admin/reports'
      path: '/admin/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof DashboardAdminReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/funding': {
      id: '/dashboard/admin/funding'
      path: '/admin/funding'
      fullPath: '/dashboard/admin/funding'
      preLoaderRoute: typeof DashboardAdminFundingRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSuggestionsRoute: typeof DashboardSuggestionsRoute
  DashboardTalentsRoute: typeof DashboardTalentsRoute
  DashboardVotesRoute: typeof DashboardVotesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminFundingRoute: typeof DashboardAdminFundingRoute
  DashboardAdminReportsRoute: typeof DashboardAdminReportsRoute
  DashboardAdminVerifyRoute: typeof DashboardAdminVerifyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSuggestionsRoute: DashboardSuggestionsRoute,
  DashboardTalentsRoute: DashboardTalentsRoute,
  DashboardVotesRoute: DashboardVotesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminFundingRoute: DashboardAdminFundingRoute,
  DashboardAdminReportsRoute: DashboardAdminReportsRoute,
  DashboardAdminVerifyRoute: DashboardAdminVerifyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  ReportsRoute: ReportsRoute,
  TalentsRoute: TalentsRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
